# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_Created',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('travel_start', models.DateTimeField(auto_now=True)),
                ('travel_end', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to='logreg_app.User')),
                ('joined_by', models.ManyToManyField(related_name='trips_joined', to='logreg_app.User')),
            ],
        ),
    ]
